### ISSUE TITLE
RoomId是什么？

### ISSUE THREAD

**Issue by Qyanlong** [lakeinchina/FloatingBili#1]
首先感谢你分享的项目。
在运行项目的时候，EditText是要输入房间号。 而这个房间号我并不清楚该输入什么内容。能否讲解一下？或者方便的话使用邮件或者QQ和你沟通一下？

**Comment by lakeinchina** [comment]
不好意思只是自己以前做着玩的东西，都没写怎么用。
那个EditText是输入直播房间的url（[http://live.bilibili.com/115](http://live.bilibili.com/115)），然后点击解析，打开网页之后点击h5播放器开始播，等下面播放地址解析出来之后点右下角的按钮。
刚刚试了下还能用，说明b站还没改版2333
悬浮窗权限也没处理，得手动开一下

**Comment by Qyanlong** [comment]
3Q，感谢答复。最近在看直播类的东西。借鉴借鉴。
